"""empty message

Revision ID: ae7f02092f7a
Revises: 
Create Date: 2023-04-21 07:16:55.238625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7f02092f7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conputadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videojuegos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contrato')
    op.drop_table('persona')
    op.drop_table('contrato_persona')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_persona',
    sa.Column('idpersona', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('idcontrato', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('persona',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('edad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='persona_pkey')
    )
    op.create_table('contrato',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nocontrato', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('costo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fechainicio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fechafin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contrato_pkey')
    )
    op.drop_table('videojuegos')
    op.drop_table('peliculas')
    op.drop_table('musica')
    op.drop_table('libros')
    op.drop_table('conputadoras')
    # ### end Alembic commands ###
