# Generated by Django 4.2 on 2023-04-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
